### ISSUE TITLE
Add Application Insights monitoring to Node services

### ISSUE THREAD

**Issue by benc-uk** [benc-uk/smilr#19]
Because App Insights is cool

**Comment by visheshbalani** [comment]
Hi,
Can this be done by adding app insights instruction key to the env variable in the data api folder? Are there any other steps to this?

**Comment by visheshbalani** [comment]
Similarly, how does one link the mongodb db to cosmosdb? I have changed the mongo_connstr to the one given in azure portal. The mongo image is used

**Comment by visheshbalani** [comment]
I sorted this out by using a combination of the deployment files present under load balancer https://github.com/benc-uk/microservices-demoapp/blob/master/kubernetes/readme.md instead of the ones given in the tutorial https://azurecitadel.github.io/labs/kubernetes
