### ISSUE TITLE
agree data format to allow PowerBI reports

### ISSUE THREAD

**Issue by davidgristwood** [benc-uk/smilr#3]
need to agree persisted data format to allow reporting on mutltiple events, and across topics, etc

**Comment by benc-uk** [comment]
Simple reporting screen has been added to the app, but PowerBI is a much better idea!

**Comment by benc-uk** [comment]
I have PowerBI working directly against the Cosmos DB documents and collections. 
It works pretty well

Two issues to investigate:
 - The connector is beta and only works in PowerBI desktop
 - Need some input from PowerBI guru on some of the query/joins we need to do
