### ISSUE TITLE
Failing

### ISSUE THREAD

**Issue by atulraizada** [benc-uk/smilr#30]
It is failing while pushing it to ACR at
Step 8/13 : RUN apk update && apk add bash
 ---> Running in 32a3d839e951
/bin/sh: 1: apk: not found

It worked fine until yesterday, something changed today.

**Comment by benc-uk** [comment]
Hi @atulraizada 
Yes I did something silly to my Dockerfile, it's fixed now

**Comment by benc-uk** [comment]
Fixed by 67ab66715e971a3deaf13b3cb7226758d60a84ad 
Closing

**Comment by atulraizada** [comment]
Thanks Ben,
Regards,

Atul Raizada
Group Manager - Infrastructure Consulting
Avanade
Mobile: +1.2489335609
Skype:   +1.3124296186
Email: atul.k.raizada@avanade.com<mailto:atul.k.raizada@avanade.com>
www.avanade.com<http://www.avanade.com/>
[azure-solutions-architect-expert-600x600]  [azure-security-engineer-associate600x600]
[Avanade logo]
In the US or Canada and need answers now? Try PING<https://amrops01.service-now.com/avanade>
